env:
  SWIFT_CACHE_PATH: .cache

steps:
  - label: ":swift: Build"
    key: "build"
    command: "cd example-project && swift build --cache-path $SWIFT_CACHE_PATH"
    plugins:
      - artifacts#v1.9.3:
          upload: "$SWIFT_CACHE_PATH"
          compressed: cache.tgz

  - label: ":swift: Lint"
    command: "swiftlint"

  - label: ":swift: Test"
    command: "cd example-project && swift test --cache-path $SWIFT_CACHE_PATH"
    depends_on: ["build"]
    plugins:
      - artifacts#v1.9.3:
          download: "$SWIFT_CACHE_PATH"
          compressed: cache.tgz
