cache:
  paths:
    - .cache

env:
  SWIFT_CACHE_PATH: .cache

steps:
  - label: ":swift: Build"
    key: "build"
    command: "cd example-project && swift build --cache-path $SWIFT_CACHE_PATH"

  - label: ":swift: Lint"
    command: "swiftlint"

  - label: ":swift: Test"
    command: "cd example-project && swift test --cache-path $SWIFT_CACHE_PATH"
    depends_on: ["build"]
